# Qualquer bug, chame a Desenvolvedora no Discord
# Discord: Maria_BR#4870
#
# Para receber suporte e retirar dúvidas sobre este plugin, entre em meu Discord
# Discord: https://discord.gg/rBDYYbg9pb

Usar prefix: true
Prefix: '&6&lCOMANDOS &8»'